"""scikit-learn adapter."""

from __future__ import annotations

from . import FrameworkAdapter

_TRANSFORMERS = {
    "StandardScaler",
    "MinMaxScaler",
    "MaxAbsScaler",
    "RobustScaler",
    "Normalizer",
    "QuantileTransformer",
    "PowerTransformer",
    "PolynomialFeatures",
    "SimpleImputer",
    "KNNImputer",
    "IterativeImputer",
    "OneHotEncoder",
    "OrdinalEncoder",
    "LabelEncoder",
    "TargetEncoder",
    "PCA",
    "TruncatedSVD",
    "KernelPCA",
    "FactorAnalysis",
    "NMF",
    "FastICA",
    "Binarizer",
    "FunctionTransformer",
    "ColumnTransformer",
    "VarianceThreshold",
    "TfidfVectorizer",
    "CountVectorizer",
    "HashingVectorizer",
}

_FEATURE_SELECTORS = {
    "SelectKBest",
    "SelectPercentile",
    "SelectFromModel",
    "RFE",
    "RFECV",
    "SequentialFeatureSelector",
    "VarianceThreshold",
    "GenericUnivariateSelect",
}

_ESTIMATORS = {
    "LogisticRegression",
    "LinearRegression",
    "Ridge",
    "Lasso",
    "ElasticNet",
    "SGDClassifier",
    "SGDRegressor",
    "SVC",
    "SVR",
    "LinearSVC",
    "KNeighborsClassifier",
    "KNeighborsRegressor",
    "DecisionTreeClassifier",
    "DecisionTreeRegressor",
    "RandomForestClassifier",
    "RandomForestRegressor",
    "GradientBoostingClassifier",
    "GradientBoostingRegressor",
    "HistGradientBoostingClassifier",
    "HistGradientBoostingRegressor",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "AdaBoostClassifier",
    "GaussianNB",
    "MultinomialNB",
    "MLPClassifier",
    "MLPRegressor",
    "KMeans",
}

_METRICS = {
    # name -> (y_true index, y_pred index)
    "accuracy_score": (0, 1),
    "balanced_accuracy_score": (0, 1),
    "f1_score": (0, 1),
    "precision_score": (0, 1),
    "recall_score": (0, 1),
    "roc_auc_score": (0, 1),
    "average_precision_score": (0, 1),
    "log_loss": (0, 1),
    "mean_squared_error": (0, 1),
    "mean_absolute_error": (0, 1),
    "r2_score": (0, 1),
    "confusion_matrix": (0, 1),
    "classification_report": (0, 1),
}


_SEEDED = {
    "RandomForestClassifier",
    "RandomForestRegressor",
    "GradientBoostingClassifier",
    "GradientBoostingRegressor",
    "HistGradientBoostingClassifier",
    "HistGradientBoostingRegressor",
    "ExtraTreesClassifier",
    "ExtraTreesRegressor",
    "AdaBoostClassifier",
    "DecisionTreeClassifier",
    "DecisionTreeRegressor",
    "SGDClassifier",
    "SGDRegressor",
    "LogisticRegression",
    "MLPClassifier",
    "MLPRegressor",
    "KMeans",
    "SVC",
    "train_test_split",
    "KFold",
    "StratifiedKFold",
    "ShuffleSplit",
    "RandomizedSearchCV",
}


def adapter() -> FrameworkAdapter:
    return FrameworkAdapter(
        name="sklearn",
        split_functions={"train_test_split", "sklearn.model_selection.train_test_split"},
        cv_splitters={
            "KFold",
            "StratifiedKFold",
            "ShuffleSplit",
            "StratifiedShuffleSplit",
            "RepeatedKFold",
            "RepeatedStratifiedKFold",
            "LeaveOneOut",
            "LeavePOut",
            "GroupKFold",
            "StratifiedGroupKFold",
            "GroupShuffleSplit",
            "LeaveOneGroupOut",
            "TimeSeriesSplit",
        },
        group_cv_splitters={
            "GroupKFold",
            "StratifiedGroupKFold",
            "GroupShuffleSplit",
            "LeaveOneGroupOut",
            "LeavePGroupsOut",
        },
        temporal_cv_splitters={"TimeSeriesSplit"},
        transformers=_TRANSFORMERS,
        stateless_transformers={
            "Normalizer",
            "Binarizer",
            "FunctionTransformer",
            "HashingVectorizer",
        },
        estimators=_ESTIMATORS,
        feature_selectors=_FEATURE_SELECTORS,
        pipeline_constructors={
            "Pipeline",
            "make_pipeline",
            "ColumnTransformer",
            "make_column_transformer",
        },
        search_constructors={
            "GridSearchCV",
            "RandomizedSearchCV",
            "HalvingGridSearchCV",
            "HalvingRandomSearchCV",
            "cross_val_score",
            "cross_validate",
            "cross_val_predict",
        },
        metrics=_METRICS,
        imbalance_sensitive_metrics={"accuracy_score"},
        seeded_callables=_SEEDED,
    )
